name: PHP Composer

on:
  push:
    branches: ['1.x', '2.x']
  pull_request:
    branches: ['1.x', '2.x']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composer: [highest, lowest]
        php-versions: ['8.1', '8.2']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - uses: "ramsey/composer-install@v2"
      with:
        dependency-versions: ${{ matrix.composer }}

    - name: Run test suite
      run: composer test
